### PR TITLE
Jonathan Wiley solution

### PR DESCRIPTION
**Pull request by jonathanwiley**
Yay for code challenges! Would love feedback on this. I was able to get the classes implemented in a way that conformed to the protocols and got the tests to pass. That said, I was unable to extract any of my functions into the protocol extension. I'm running into issues doing that because I need to keep state (namely a reference to the head of the list) in order to implement the linked list, and protocol extensions can only be used for purely functional extractions. Is my reasoning correct or am I missing something here?

### CODE REVIEW

**Comment by patgoley** [comment]
@microchip128 Great job getting everything working! One or two things that will help you out:

In Swift (and most languages) iterators are meant to be single-use, throw away objects that aren't reused. This is because they're usually stateful (e.g. the `currentNode` property). If the LinkedList itself is the iterator, we've no way to reset currentNode if we bail out of an iteration early. The next time we iterate we'd pick up where the last loop left off.

Instead of conforming LinkedList to IteratorProtocol, try implementing `makeIterator` from sequence which will create a new iterator for each caller. Try implementing with AnyIterator or define your own custom Iterator type that tracks the current node.

My fault for not writing a unit test to catch this :)

**Comment by jonathanwiley** [comment]
Hey @patgoley, thanks for the tips! I conformed my LinkedList to Sequence instead of IteratorProtocol as you suggested and used an AnyIterator to implement my iterator. With this approach I was even able to extract the LinkedListType conformance to Sequence out into a protocol extension so there's a default implementation! Before, I needed to store state for the next() function required by IteratorProtocol, but since I switched to Sequence I could keep the state I needed in the iterator object I return. Very cool.

I even updated this with a new test :) Any feedback welcome here. 

Thanks for putting this together, definitely learned some new things about protocols!

**Comment by patgoley** [comment]
@microchip128 Nice job!! This ended up looking almost exactly like my implementation. And yes, the makeIterator method is the one thing that can be moved to the protocol extension here, so nice work on realizing that.

I'd love to merge in your solution here, but one thing first. If you could copy the whole project into a new directory with your name instead of modifying the /Challenge Source project, that will keep us all from stepping on each other toes and let us merge them all together. Thanks for taking up the challenge here and congrats on finding the solution! 🎉

**Comment by jonathanwiley** [comment]
Hey @patgoley, haha, I need to get better at reading instructions. I removed my changes to the base tests file so the original project is untouched.

**Pull request merged**
