### PR TITLE
mohssen_fathi_solution

### PR DESCRIPTION
**Pull request by mohssenfathi**
This passes all the tests, however I'm struggling to find a way to move anything to the protocol's default implementation. Any suggestions would be great @patgoley

### CODE REVIEW

**Comment by mohssenfathi** [comment]
Ha. Just read Wiley's comment. Sounds like we have the same problem...

**Comment by patgoley** [comment]
@mohssenfathi Looks great! My solution was slightly different which allowed me to move the iterator logic to a protocol extension. I didn't think about conforming LinkedList to IteratorProtocol but it seems like that works for all of the tests here. I think it would break however if you did a partial iteration of the linked list, because the next time you went to iterate it, the `current` property would be pointed to a node somewhere in the middle of the list. This is generally why iterators are single-use only, because they often need to track state.

My solution involved implementing the `makeIterator` returning an `AnyIterator`, instead of conforming LinkedList to IteratorProtocol. If you want to take another stab, you may want to give that a try.

**Comment by mohssenfathi** [comment]
Ah cool. I was wondering about that actually. I'll give it another shot using makeIterator. Thanks for the feedback.

**Comment by mohssenfathi** [comment]
Changed some stuff up like you suggested @patgoley . This allowed me to move some Sequence conformance things to the protocol. I'm still not seeing a way to pass the performance tests without modifying the protocols though...

**Comment by patgoley** [comment]
@mohssenfathi One hint is you may need to add something to your class that is not expressed in the protocol. This would be a part of your private API to achieve better performance, but not important to the public interface.

**Comment by patgoley** [comment]
Actually it looks like you have what I'm talking about, a `tail` reference. If used correctly, then both appending and prepending should be constant time, just updating a reference. Which perf test is still failing?

**Comment by mohssenfathi** [comment]
Ah sorry. I wasn't super clear there. All the tests pass. I was just saying that I don't see a way to provide append/prepend as default implementations without removing `tail`.

**Comment by patgoley** [comment]
@mohssenfathi Oh yeah, you're right about that. I was only able to get the iterator logic moved to a protocol extension. This all looks great, congrats on completing this coding challenge! 🎉

**Pull request merged**
